name: PR CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  pr:
    uses: ./.github/workflows/ci.yml
    with:
      project_path: './src/Workflow.Api/Workflow.Api.csproj'
      branch: ${{ github.sha }}
    secrets: inherit
