name: CI

on: 
  workflow_call:
    inputs:
      project_path:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.branch }}

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
        
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ${{ inputs.project_path }} --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal
