name: Update Tag

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull Image
        run: docker pull -a ${{ inputs.image }}

      - name: Update tag
        run: |
          docker tag ${{ inputs.image }}:${{ inputs.image_tag }} ${{ inputs.image }}:${{ inputs.tag }}
          docker tag ${{ inputs.image }}:${{ inputs.image_tag }} ${{ inputs.image }}:deployed-${{ inputs.tag }}

      - name: Push new image
        run: docker push -a ${{ inputs.image }}
